# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8mBh_GMt-C1a-nzUEemwRojZc2sOJQV
"""

from google.colab import drive
drive.mount('/content/drive')
!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()

!pip install roboflow
import os
from roboflow import Roboflow
rf = Roboflow(api_key="GmQsi4xUnOdFuC7cWGu2")
project = rf.workspace("widians-workspace").project("meja-c4jhe")
version = project.version(2)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8n.pt data={dataset.location}/data.yaml epochs=50 imgsz=640 plots=True

import shutil
destination_folder = '/content/drive/MyDrive/Project_Deteksi_Meja'
shutil.copytree('/content/runs/detect/train', destination_folder)

print(f"Hasil training sudah di Google Drive folder: {destination_folder}")

import os
from IPython.display import Image, display
runs_dir = '/content/runs/detect'
latest_train = max([os.path.join(runs_dir, d) for d in os.listdir(runs_dir)], key=os.path.getmtime)
print(f"Membuka hasil tes dari folder: {latest_train}")
gambar_prediksi = os.path.join(latest_train, 'val_batch0_pred.jpg')

if os.path.exists(gambar_prediksi):
    display(Image(filename=gambar_prediksi, width=800))
else:
    print("Gambar prediksi belum ada.")

import os
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
runs_dir = '/content/runs/detect'
latest_train = max([os.path.join(runs_dir, d) for d in os.listdir(runs_dir)], key=os.path.getmtime)
path_matrix = os.path.join(latest_train, 'confusion_matrix.png')
if os.path.exists(path_matrix):
    img = mpimg.imread(path_matrix)
    plt.figure(figsize=(5, 5))
    plt.imshow(img)
    plt.axis('off')
    plt.show()
else:
    print("Coba cek folder runs/detect/train.")